fn main() {
    let a = 2;
    let a0 = 2;
    let a_c = 2;
    let a0_c0 = 2;
    let a-b = 2;
    let a0-b2 = 2;
    let a_long_name_with_underscores_in_between = 2;
    let a-long-name-with-dashes-in-between = 2;
    let numbers12345in12345between12345 = 2;

    let A = 2;
    let A0 = 2;
    let A_C = 2;
    let A0_C0 = 2;
    let AB-CD = 2;
    let A_LONG_NAME_WITH_UNDERSCORES_IN_BETWEEN = 2;
    let A-LONG-NAME-WITH-DASHES-IN-BETWEEN = 2;

    let aA = 2;
    let a0Aa1a = 2;
    let a_C = 2;
    let A_c = 2;
    let Aa-aA = 2;
    let aA_Aa = 2;

    print_number(aA_Aa);
}