fn main() {
    let a = false;
    let b = !false;

    if b {
        print_number(1);
    } else {
        print_number(2);
    }

    if !b {
        print_number(3);
    } else {
        print_number(4);
    }

    let c = !a;
    if c {
        print_number(5);
    } else {
        print_number(6);
    }

    if !(a == b) {
        print_number(7);
    } else {
        print_number(8);
    }
}