[package]
name = "test_generator_macro"
version = "0.1.0"
authors = ["Vidar Magnusson <git@vidarmagnusson.com>"]
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "1", features = ["full"] }
quote = "1"
